export const ADD = 'ADD'
export const MINUS = 'MINUS'
export const GET_PAGE_SUM = 'GET_PAGE_SUM'
export const ADD_ANSWER = 'ADD_ANSWER'
export const GET_PAGE_INFO = 'GET_PAGE_INFO'
export const ADD_TIMESTAMP = 'ADD_TIMESTAMP'
